"""Write `docs/cli-reference.md` from the command tree of `osh`.

The text comes from the command objects, never from a rendered `--help`, so the page does not
depend on the terminal. `--check` writes nothing and fails when the page is stale.
"""

import argparse
import re
import sys
from collections.abc import Iterator, Sequence
from enum import Enum
from pathlib import Path
from typing import Any

import typer
from typer.core import TyperArgument, TyperGroup, TyperOption

from odouche_cli.app import app


PAGE = Path(__file__).resolve().parent.parent / "docs" / "cli-reference.md"
REGENERATE = "make docs-cli"

_HEADER = f"""\
# CLI reference

<!-- Generated by `{REGENERATE}` from the command tree of `osh`. Do not edit. -->

Every command of `osh` with its arguments and options, generated from the application.
The [guide](cli.md) has what a command's help does not say: how the project and the branch are
found, the output, the exit codes and the environment variables.

Every command also takes `--help`.
"""
_EXAMPLE = "Example: "
_HELP_OPTION = "help"
_STATED_DEFAULT = "Default:"
_CODE = re.compile(r"`[^`]*`")
# Every control character but the line break, click's `\b` and `\f` markers among them.
_CONTROL = re.compile(r"[\x00-\x09\x0b-\x1f\x7f-\x9f]")


class UnsupportedError(Exception):
    """A command or a parameter the page has no rendering for."""


def render(application: typer.Typer | None = None) -> str:
    """Return the page for an application, which is `osh` unless a test gives another."""
    root = typer.main.get_command(app if application is None else application)
    blocks = [_HEADER.rstrip("\n")]
    for context in _walk(typer.Context(root, info_name=root.name)):
        blocks.extend(_command(context))
    return "\n\n".join(blocks) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    """Write the page, or with `--check` only tell whether it is the one in the tree."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Write nothing, and fail when the page is stale.")
    options = parser.parse_args(argv)
    try:
        page = render()
    except UnsupportedError as error:
        sys.stderr.write(f"{error}\n")
        return 2
    if not options.check:
        PAGE.write_text(page, encoding="utf-8")
        return 0
    if PAGE.is_file() and PAGE.read_text(encoding="utf-8") == page:
        return 0
    sys.stderr.write(f"docs/{PAGE.name} is not what the commands of `osh` give. Run `{REGENERATE}`.\n")
    return 1


def _walk(context: typer.Context) -> Iterator[typer.Context]:
    """Yield the context of a command, then of each command under it."""
    yield context
    for child in _children(context):
        yield from _walk(child)


def _children(context: typer.Context) -> list[typer.Context]:
    """Return the contexts of the commands of a group, in the order its help lists them."""
    group = context.command
    if not isinstance(group, TyperGroup):
        return []
    commands = [(name, group.get_command(context, name)) for name in group.list_commands(context)]
    return [
        typer.Context(command, info_name=name, parent=context)
        for name, command in commands
        if command is not None and not command.hidden
    ]


def _command(context: typer.Context) -> list[str]:
    """Return the blocks of one command: its heading, help, usage, parameters, example and commands."""
    command = context.command
    path = context.command_path
    # A command of a group sits one level under it. The root and its own commands share the top one.
    level = 2 + max(0, len(path.split()) - 2)
    blocks = [f"{'#' * level} `{path}`"]
    text = _checked(command.help or "", f"The help of `{path}`")
    blocks.extend(paragraph.strip() for paragraph in text.split("\n\n") if paragraph.strip())
    blocks.append(f"```text\n{' '.join([path, *command.collect_usage_pieces(context)])}\n```")
    parameters = [
        parameter
        for parameter in command.get_params(context)
        if isinstance(parameter, (TyperArgument, TyperOption))
        and parameter.name != _HELP_OPTION
        and not parameter.hidden
    ]
    for parameter in parameters:
        _check(parameter, path)
    arguments = [parameter for parameter in parameters if isinstance(parameter, TyperArgument)]
    options = [parameter for parameter in parameters if isinstance(parameter, TyperOption)]
    if arguments:
        rows = [(f"`{_metavar(argument)}`", _description(argument)) for argument in arguments]
        blocks.append(_table(("Argument", "Description"), rows))
    if options:
        rows = [(_flags(option), _description(option), _variable(option)) for option in options]
        blocks.append(_table(("Option", "Description", "Environment"), rows))
    children = _children(context)
    epilog = _checked(command.epilog or "", f"The epilog of `{path}`")
    # A group's example is the one its command gives right below.
    if epilog and not (children and epilog.startswith(_EXAMPLE)):
        blocks.append(_epilog(epilog))
    if children:
        rows = [
            (f"[`{child.command_path}`](#{child.command_path.replace(' ', '-')})", _summary(child.command.help))
            for child in children
        ]
        blocks.append(_table(("Command", "Description"), rows))
    return blocks


def _check(parameter: TyperArgument | TyperOption, path: str) -> None:
    """Fail on a parameter the page would show wrongly, naming it and its command."""
    name = parameter.opts[0] if isinstance(parameter, TyperOption) else _metavar(parameter)
    where = f"`{name}` of `{path}`"
    _checked(parameter.help or "", f"The help of {where}")
    if parameter.default == "":
        msg = f"{where} has an empty default, which the page cannot show."
        raise UnsupportedError(msg)
    if isinstance(parameter.default, list | tuple):
        msg = f"{where} has several values as its default, which the page cannot show."
        raise UnsupportedError(msg)
    if isinstance(parameter, TyperOption) and parameter.show_default is not True:
        msg = f"{where} sets `show_default`, which the page does not follow."
        raise UnsupportedError(msg)
    if isinstance(parameter, TyperOption):
        return
    if parameter.envvar:
        msg = f"{where} is an argument that reads an environment variable, which the page does not show."
        raise UnsupportedError(msg)
    if _has_default(parameter):
        msg = f"{where} is an argument with a default, which the page does not show."
        raise UnsupportedError(msg)


def _checked(text: str, what: str) -> str:
    """Return text that Markdown shows as it is written, and fail on any other."""
    if _CONTROL.search(text):
        msg = f"{what} has a control character or a `\\b` marker, which the page cannot show."
        raise UnsupportedError(msg)
    if re.search("[<>]", _CODE.sub("", text)):
        msg = f"{what} has `<` or `>` outside backticks, which Markdown reads as HTML."
        raise UnsupportedError(msg)
    return text


def _flags(option: TyperOption) -> str:
    """Return the names of an option, the long ones first, with what stands for its value."""
    names = sorted(option.opts, key=lambda name: not name.startswith("--"))
    if option.is_flag or option.count:
        return ", ".join(f"`{name}`" for name in [*names, *option.secondary_opts])
    return ", ".join(f"`{name} {_metavar(option)}`" for name in names)


def _metavar(parameter: TyperArgument | TyperOption) -> str:
    """Return what stands for a parameter's value: the one it declares, or its own name in capitals."""
    name = max(parameter.opts, key=len).lstrip("-") if isinstance(parameter, TyperOption) else parameter.name or ""
    return parameter.metavar or name.replace("-", "_").upper()


def _description(parameter: TyperArgument | TyperOption) -> str:
    """Return a parameter's help, then what the help may not say: required, choices, range and default."""
    text = _line(parameter.help or "")
    said = [text]
    if parameter.required:
        said.append("Required.")
    kind: Any = parameter.type
    choices: Sequence[object] | None = getattr(kind, "choices", None)
    if choices:
        said.append(f"One of {', '.join(f'`{_value(choice)}`' for choice in choices)}.")
    lowest, highest = getattr(kind, "min", None), getattr(kind, "max", None)
    if lowest is not None and highest is not None:
        said.append(f"From {lowest} to {highest}.")
    elif lowest is not None:
        said.append(f"At least {lowest}.")
    elif highest is not None:
        said.append(f"At most {highest}.")
    default = _default(parameter) if isinstance(parameter, TyperOption) else ""
    if default and _STATED_DEFAULT not in text:
        said.append(f"{_STATED_DEFAULT} `{default}`.")
    return " ".join(part for part in said if part)


def _has_default(parameter: TyperArgument | TyperOption) -> bool:
    """Tell whether a parameter has a value when it is not given, and not one computed at run time."""
    default: object = parameter.default
    return not (default is None or callable(default))


def _default(option: TyperOption) -> str:
    """Return what an option is when it is not given, or nothing for no value, a count and a flag with no off name."""
    default: object = option.default
    if not _has_default(option) or option.count:
        return ""
    if default is True:
        return option.opts[0]
    if default is False:
        return option.secondary_opts[0] if option.secondary_opts else ""
    return _value(default)


def _variable(option: TyperOption) -> str:
    variables = [option.envvar] if isinstance(option.envvar, str) else list(option.envvar or ())
    return ", ".join(f"`{variable}`" for variable in variables)


def _value(value: object) -> str:
    return str(value.value if isinstance(value, Enum) else value)


def _epilog(epilog: str) -> str:
    """Return a command's epilog, with the example it gives as a block to copy."""
    if not epilog.startswith(_EXAMPLE):
        return epilog.strip()
    return f"Example:\n\n```bash\n{epilog.removeprefix(_EXAMPLE).strip()}\n```"


def _summary(text: str | None) -> str:
    """Return the first paragraph of a command's help."""
    return _line((text or "").split("\n\n")[0])


def _line(text: str) -> str:
    """Make text one line that a table cell can hold."""
    return " ".join(text.split()).replace("|", "\\|")


def _table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> str:
    lines = [headers, ["---"] * len(headers), *rows]
    # An empty cell is one space wide, as markdownlint leaves it.
    return "\n".join("|" + "|".join(f" {cell} " if cell else " " for cell in cells) + "|" for cells in lines)


if __name__ == "__main__":
    sys.exit(main())
