"""Write `docs/mcp-reference.md` from the tools of `odouche-mcp`.

The text comes from the tools the server registers with `--allow-changes`, which is all of them.
`--check` writes nothing and fails when the page is stale.
"""

import asyncio
import json
import re
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from mcp.server import MCPServer
from mcp.types import Tool

import _reference
from _reference import UnsupportedError
from odouche_mcp._contract import BOUNDS, RETURNS, TOUCHES
from odouche_mcp.server import create_server


PAGE = Path(__file__).resolve().parent.parent / "docs" / "mcp-reference.md"
REGENERATE = "make docs-mcp"

_HEADER = f"""\
# MCP reference

<!-- Generated by `{REGENERATE}` from the tools of `odouche-mcp`. Do not edit. -->

Every tool of `odouche-mcp` with its arguments, what it returns, what it can touch on Odoo.sh and
its bounds, generated from the server. The [guide](mcp.md) has what a tool's description does not
say: the setup, the session, the security measures and what to do about an error.

A tool that changes Odoo.sh is registered only when the server is started with
[`--allow-changes`](mcp.md#changing-state).
"""
_LABELS = (RETURNS, TOUCHES, BOUNDS)
# As a client reads them.
_HINTS = ("readOnlyHint", "destructiveHint", "idempotentHint", "openWorldHint")
# What the page shows of an argument. Any other keyword would be left out without a word.
_SHOWN = frozenset({"title", "type", "default", "anyOf", "$ref"})
_NULL = {"type": "null"}
_SCALARS = frozenset({"string", "integer", "number", "boolean"})
_REFERENCE = "#/$defs/"
_CODE = re.compile(r"`[^`]*`")
_CONTROL = re.compile(r"[\x00-\x1f\x7f-\x9f]")


def render(server: MCPServer[Any] | None = None) -> str:
    """Return the page for a server, which is the one with every tool unless a test gives another."""
    tools = asyncio.run((create_server(allow_changes=True) if server is None else server).list_tools())
    described = [(tool, _described(tool)) for tool in tools]
    rows = [
        (f"[`{tool.name}`](#{tool.name})", "No" if _reads_only(tool) else "Yes", _reference.line(lines[TOUCHES]))
        for tool, (_, lines) in described
    ]
    blocks = [_HEADER.rstrip("\n"), _reference.table(("Tool", "Changes Odoo.sh", TOUCHES), rows)]
    for tool, (summary, lines) in described:
        blocks.extend(_tool(tool, summary, lines))
    return "\n\n".join(blocks) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    """Write the page, or with `--check` only tell whether it is the one in the tree."""
    return _reference.main(
        argv, render, PAGE, description=__doc__ or "", source="the tools of `odouche-mcp`", regenerate=REGENERATE
    )


def _described(tool: Tool) -> tuple[str, dict[str, str]]:
    """Split a tool's description into its summary and its labelled lines."""
    text = (tool.description or "").split("\n")
    summary, last = text[: -len(_LABELS)], text[-len(_LABELS) :]
    lines: dict[str, str] = {}
    for label in _LABELS:
        line = next((line for line in last if line.startswith(f"{label}: ")), None)
        if line is None:
            msg = f"The description of `{tool.name}` does not end with its `{label}:` line."
            raise UnsupportedError(msg)
        lines[label] = _checked(line.removeprefix(f"{label}: "), f"The `{label}:` line of `{tool.name}`")
    return _checked(" ".join(" ".join(summary).split()), f"The description of `{tool.name}`"), lines


def _hints(tool: Tool) -> list[bool]:
    given: dict[str, Any] = tool.annotations.model_dump(by_alias=True) if tool.annotations else {}
    hints = [hint for name in _HINTS if isinstance(hint := given.get(name), bool)]
    if len(hints) != len(_HINTS):
        msg = f"`{tool.name}` does not set all four hints."
        raise UnsupportedError(msg)
    return hints


def _reads_only(tool: Tool) -> bool:
    return _hints(tool)[0]


def _tool(tool: Tool, summary: str, lines: dict[str, str]) -> list[str]:
    """Return the blocks of one tool: its heading, summary, arguments, labelled lines and hints."""
    blocks = [f"## `{tool.name}`", summary]
    schema = tool.input_schema
    required: list[str] = schema.get("required", [])
    properties: dict[str, dict[str, Any]] = schema.get("properties", {})
    rows = [
        (f"`{name}`", *_argument(argument, schema, f"`{name}` of `{tool.name}`", required=name in required))
        for name, argument in properties.items()
    ]
    if rows:
        blocks.append(_reference.table(("Argument", "Type", "Default"), rows))
    blocks.append("\n".join(f"- **{label}**: {lines[label]}" for label in _LABELS))
    hints = [(f"`{hint}`", str(value).lower()) for hint, value in zip(_HINTS, _hints(tool), strict=True)]
    blocks.append(_reference.table(("Hint", "Value"), hints))
    return blocks


def _argument(argument: dict[str, Any], schema: dict[str, Any], where: str, *, required: bool) -> tuple[str, str]:
    """Return the type of an argument, and what it is when it is not given or that it has to be.

    The type is a scalar or a list of choices. An argument that may also be null is one left out.
    """
    kinds: list[dict[str, Any]] = argument.get("anyOf", [argument])
    scalars = [kind for kind in kinds if kind != _NULL]
    if argument.keys() - _SHOWN or len(scalars) != 1 or (required and len(kinds) > 1):
        msg = f"{where} has a schema the page cannot show."
        raise UnsupportedError(msg)
    kind = scalars[0]
    reference: str = kind.get("$ref", "")
    if reference.startswith(_REFERENCE):
        kind = schema.get("$defs", {}).get(reference.removeprefix(_REFERENCE), {})
    choices: list[object] | None = kind.get("enum")
    name: object = kind.get("type")
    if name not in _SCALARS or "const" in kind:
        msg = f"{where} has a schema the page cannot show."
        raise UnsupportedError(msg)
    default: object = argument.get("default")
    cells = (
        "one of " + ", ".join(f"`{choice}`" for choice in choices) if choices else str(name),
        "Required." if required else "" if default is None else f"`{json.dumps(default)}`",
    )
    if any(re.search(r"[|\n]", cell) or cell.count("`") % 2 or "``" in cell for cell in cells):
        msg = f"{where} has a choice or a default a table cell cannot hold."
        raise UnsupportedError(msg)
    return cells


def _checked(text: str, what: str) -> str:
    """Return text that Markdown shows as it is written, and fail on any other."""
    if _CONTROL.search(text):
        msg = f"{what} has a control character, which the page cannot show."
        raise UnsupportedError(msg)
    if re.search("[<>]", _CODE.sub("", text)):
        msg = f"{what} has `<` or `>` outside backticks, which Markdown reads as HTML."
        raise UnsupportedError(msg)
    return text


if __name__ == "__main__":
    sys.exit(main())
